baseURL = 'https://walls.dev'
languageCode = 'en-us'
title = 'Software Engineer (ex-Google)'
# theme = 'anatole'
enableEmoji = true
enableRobotsTXT = true
summaryLength = 30

[module]
  # uncomment line below for temporary local development of module
  # replacements = "github.com/lxndrblz/anatole -> ../../anatole"
  [[module.imports]]
    path = "github.com/dinosoeren/anatole"
    disable = false
  [[module.imports]]
    path = "github.com/flypenguin/hugo-shortcode-gallery"

[params]
  title = "Soeren Walls"
  author = "Soeren Walls"
  description = "NJ-born Software Engineer from Pueblo, CO with a liberal arts degree in CS & Theatre, and a passion for storytelling, travel, and singing a-capella."
  profilePicture = "images/profile.jpeg"
  images = ["images/profile.jpeg"]

  postSections = ["blog", "project"]
  mainSections = ["blog", "project"]
  relatedPosts = true
  readMore = true
  numberOfRelatedPosts = 3
  # disableTitleCapitalization = true
  oldContentWarning = true
  oldContentDuration = 365
  enableMediumZoom = false

  customCss = ["css/custom.css"]
  gtagId = "G-NX48YN18V3"
  contactFormAction = "https://formspree.io/f/mgvybvzd"

  pygmentsCodeFences = true
  pygmentsUseClasses = true

  [params.lightgallery.defaults]
    speed = 500
    thumbformat = "webp"
    thumbquality = "q70"
    thumbsize = "250x250"
    thumbtype = "fill"
    transition = "lg-slide"

  [params.giscus]
    repo = "dinosoeren/walls.dev"
    repoID = "R_kgDOOVK_og"
    category = "Comments"
    categoryID = "DIC_kwDOOVK_os4Csinc"

  ## Math settings
  [params.math]
    enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
    use = "katex"  # options: "katex", "mathjax". default is "katex".

  [[params.socialIcons]]
    icon = "fab fa-linkedin"
    title = "LinkedIn"
    url = "https://linkedin.com/in/soerenw"
  [[params.socialIcons]]
    icon = "fab fa-github"
    title = "GitHub"
    url = "https://github.com/dinosoeren"
  [[params.socialIcons]]
    icon = "fab fa-youtube"
    title = "YouTube"
    url = "https://youtube.com/@dinosoeren"
  [[params.socialIcons]]
    icon = "fab fa-spotify"
    title = "Spotify"
    url = "https://open.spotify.com/track/1cHVzM29SkVmIdqR1F3xem"

[menu]
  [[menu.main]]
    name = "Home"
    identifier = "home"
    weight = 100
    url = "/"

  [[menu.main]]
    name = "Projects"
    weight = 200
    identifier = "projects"
    url = "/project/"

  [[menu.main]]
    name = "Blog"
    weight = 400
    identifier = "blog"
    url = "/blog/"

  [[menu.main]]
    name = "About"
    weight = 500
    identifier = "about"
    url = "/about/"

  [[menu.main]]
    name = "Contact"
    weight = 600
    identifier = "contact"
    url = "/contact/"
