# local_backend: true # uncomment for local dev and run npx decap-server
backend:
  name: git-gateway
  repo: dinosoeren/walls.dev
  branch: main
media_folder: static/images
public_folder: /images
collections:
  - name: 'project'
    label: 'Project'
    folder: 'content/project'
    path: '{{slug}}/index.md'
    media_folder: images
    public_folder: /images
    create: true
    slug: '{{slug}}'
    preview_path: 'project/{{slug}}'
    editor:
      preview: true
    view_groups:
      - label: Year
        field: date
        pattern: \d{4}
      - label: Category
        field: categories
    view_filters:
      - label: Drafts
        field: draft
        pattern: true
    fields:
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Draft', name: 'draft', widget: 'boolean', required: false }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Summary', name: 'summary', widget: 'string', required: false }
      - { label: 'External URL', name: 'redirectUrl', widget: 'string', required: false }
      - { label: 'Thumbnail', name: 'thumbnail', widget: 'image', required: false }
      - { label: 'Categories', name: 'categories', widget: 'list' }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'AI Chat', name: 'ai_chat', widget: 'ai-chat', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    path: '{{slug}}/index.md'
    media_folder: images
    public_folder: /images
    create: true
    slug: '{{slug}}'
    preview_path: 'blog/{{slug}}'
    editor:
      preview: true
    view_groups:
      - label: Year
        field: date
        pattern: \d{4}
      - label: Category
        field: categories
    view_filters:
      - label: Drafts
        field: draft
        pattern: true
    fields:
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Draft', name: 'draft', widget: 'boolean', required: false }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Summary', name: 'summary', widget: 'string', required: false }
      - { label: 'External URL', name: 'redirectUrl', widget: 'string', required: false }
      - { label: 'Thumbnail', name: 'thumbnail', widget: 'image', required: false }
      - { label: 'Tags', name: 'tags', widget: 'list' }
      - { label: 'Categories', name: 'categories', widget: 'list' }
      - { label: 'AI Chat', name: 'ai_chat', widget: 'ai-chat', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
